[package]
name = "xtask"
version = "0.1.0"
edition = "2024"

[dependencies]
clap               = "4.5.38"
tracing            = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "fmt"] }
